

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("extensionMethod.kt")
  public void testExtensionMethod() {
    runTest("compiler-plugin/testData/box/extensionMethod.kt");
  }

  @Test
  @TestMetadata("remapsOriginalSetCall.kt")
  public void testRemapsOriginalSetCall() {
    runTest("compiler-plugin/testData/box/remapsOriginalSetCall.kt");
  }

  @Test
  @TestMetadata("standardMethod.kt")
  public void testStandardMethod() {
    runTest("compiler-plugin/testData/box/standardMethod.kt");
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/control-group")
  @TestDataPath("$PROJECT_ROOT")
  public class Control_group {
    @Test
    public void testAllFilesPresentInControl_group() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/control-group"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("control.kt")
    public void testControl() {
      runTest("compiler-plugin/testData/box/control-group/control.kt");
    }

    @Test
    @TestMetadata("control2.kt")
    public void testControl2() {
      runTest("compiler-plugin/testData/box/control-group/control2.kt");
    }

    @Test
    @TestMetadata("expectedDefaultPropertySet.kt")
    public void testExpectedDefaultPropertySet() {
      runTest("compiler-plugin/testData/box/control-group/expectedDefaultPropertySet.kt");
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/box/generate-default-setter")
  @TestDataPath("$PROJECT_ROOT")
  public class Generate_default_setter {
    @Test
    public void testAllFilesPresentInGenerate_default_setter() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box/generate-default-setter"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("test1.kt")
    public void testTest1() {
      runTest("compiler-plugin/testData/box/generate-default-setter/test1.kt");
    }
  }
}
