

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("controlTest.kt")
  public void testControlTest() {
    runTest("compiler-plugin/testData/diagnostics/controlTest.kt");
  }

  @Test
  @TestMetadata("working.kt")
  public void testWorking() {
    runTest("compiler-plugin/testData/diagnostics/working.kt");
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/diagnostics/declaration")
  @TestDataPath("$PROJECT_ROOT")
  public class Declaration {
    @Test
    public void testAllFilesPresentInDeclaration() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/A no error")
    @TestDataPath("$PROJECT_ROOT")
    public class A_no_error {
      @Test
      public void testAllFilesPresentInA_no_error() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/A no error"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("extMethod.kt")
      public void testExtMethod() {
        runTest("compiler-plugin/testData/diagnostics/declaration/A no error/extMethod.kt");
      }

      @Test
      @TestMetadata("inClass.kt")
      public void testInClass() {
        runTest("compiler-plugin/testData/diagnostics/declaration/A no error/inClass.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/B target property not found")
    @TestDataPath("$PROJECT_ROOT")
    public class B_target_property_not_found {
      @Test
      public void testAllFilesPresentInB_target_property_not_found() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/B target property not found"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("extMethod.kt")
      public void testExtMethod() {
        runTest("compiler-plugin/testData/diagnostics/declaration/B target property not found/extMethod.kt");
      }

      @Test
      @TestMetadata("inClass.kt")
      public void testInClass() {
        runTest("compiler-plugin/testData/diagnostics/declaration/B target property not found/inClass.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/C target property unsupported")
    @TestDataPath("$PROJECT_ROOT")
    public class C_target_property_unsupported {
      @Test
      public void testAllFilesPresentInC_target_property_unsupported() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/C target property unsupported"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("extMethod.kt")
      public void testExtMethod() {
        runTest("compiler-plugin/testData/diagnostics/declaration/C target property unsupported/extMethod.kt");
      }

      @Test
      @TestMetadata("inClass.kt")
      public void testInClass() {
        runTest("compiler-plugin/testData/diagnostics/declaration/C target property unsupported/inClass.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/D target property not visible")
    @TestDataPath("$PROJECT_ROOT")
    public class D_target_property_not_visible {
      @Test
      public void testAllFilesPresentInD_target_property_not_visible() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/D target property not visible"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("extMethod.kt")
      public void testExtMethod() {
        runTest("compiler-plugin/testData/diagnostics/declaration/D target property not visible/extMethod.kt");
      }

      @Test
      @TestMetadata("inClass.kt")
      public void testInClass() {
        runTest("compiler-plugin/testData/diagnostics/declaration/D target property not visible/inClass.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/E cannot widen visibility")
    @TestDataPath("$PROJECT_ROOT")
    public class E_cannot_widen_visibility {
      @Test
      public void testAllFilesPresentInE_cannot_widen_visibility() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/E cannot widen visibility"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("extMethod.kt")
      public void testExtMethod() {
        runTest("compiler-plugin/testData/diagnostics/declaration/E cannot widen visibility/extMethod.kt");
      }

      @Test
      @TestMetadata("inClass.kt")
      public void testInClass() {
        runTest("compiler-plugin/testData/diagnostics/declaration/E cannot widen visibility/inClass.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/F must have single param")
    @TestDataPath("$PROJECT_ROOT")
    public class F_must_have_single_param {
      @Test
      public void testAllFilesPresentInF_must_have_single_param() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/F must have single param"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("must_have_single_param.kt")
      public void testMust_have_single_param() {
        runTest("compiler-plugin/testData/diagnostics/declaration/F must have single param/must_have_single_param.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/G parameter shadows property type")
    @TestDataPath("$PROJECT_ROOT")
    public class G_parameter_shadows_property_type {
      @Test
      public void testAllFilesPresentInG_parameter_shadows_property_type() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/G parameter shadows property type"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("test.kt")
      public void testTest() {
        runTest("compiler-plugin/testData/diagnostics/declaration/G parameter shadows property type/test.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/H must not have type params")
    @TestDataPath("$PROJECT_ROOT")
    public class H_must_not_have_type_params {
      @Test
      public void testAllFilesPresentInH_must_not_have_type_params() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/H must not have type params"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("test.kt")
      public void testTest() {
        runTest("compiler-plugin/testData/diagnostics/declaration/H must not have type params/test.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/I must not have context params")
    @TestDataPath("$PROJECT_ROOT")
    public class I_must_not_have_context_params {
      @Test
      public void testAllFilesPresentInI_must_not_have_context_params() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/I must not have context params"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("test.kt")
      public void testTest() {
        runTest("compiler-plugin/testData/diagnostics/declaration/I must not have context params/test.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/J must return unit")
    @TestDataPath("$PROJECT_ROOT")
    public class J_must_return_unit {
      @Test
      public void testAllFilesPresentInJ_must_return_unit() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/J must return unit"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("test.kt")
      public void testTest() {
        runTest("compiler-plugin/testData/diagnostics/declaration/J must return unit/test.kt");
      }
    }

    @Nested
    @TestMetadata("compiler-plugin/testData/diagnostics/declaration/Z all errors")
    @TestDataPath("$PROJECT_ROOT")
    public class Z_all_errors {
      @Test
      public void testAllFilesPresentInZ_all_errors() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/declaration/Z all errors"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
      }

      @Test
      @TestMetadata("superMembers.kt")
      public void testSuperMembers() {
        runTest("compiler-plugin/testData/diagnostics/declaration/Z all errors/superMembers.kt");
      }
    }
  }

  @Nested
  @TestMetadata("compiler-plugin/testData/diagnostics/workshop")
  @TestDataPath("$PROJECT_ROOT")
  public class Workshop {
    @Test
    public void testAllFilesPresentInWorkshop() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics/workshop"), Pattern.compile("^(.+)\\.kt$"), Pattern.compile("^(.+)\\.fir\\.kts?$"), TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("workshop.kt")
    public void testWorkshop() {
      runTest("compiler-plugin/testData/diagnostics/workshop/workshop.kt");
    }
  }
}
